config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:create, :show]
  end
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
belongs_to :user
belongs_to :instrument
end

app/models/car.rb
class Car < ApplicationRecord
	include PgSearch
	pg_search_scope :search_by_brand_and_model, against: [ :brand, :model ]
	belongs_to :user
	has_attachment :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  def self.from_omniauth(auth)  
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  def create
    user = User.from_omniauth(env["omniauth.auth"]) ## Setting "user" here
    session[:user_id] = user.id  ## Changed this to use the set "user"
    redirect_to root_url
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def create 
	end 

	def update 
	end 

	def destroy
	end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]
	 def search
    @cars_l = []
    @cars_q = Car.search_by_model_and_brand(params[:query])
    @cars_l += Car.near(params[:brand, :model], 20)
    if params[:brand, :model].blank?
      @cars = @cars_q
    elsif params[:query].blank?
      @cars = @cars_l
    else
      @cars = @cars_l.select { |elem| @cars_q.include?(elem) }
    end
     render :search
   end

	def index
		@cars = Car.all
	end 

	def show
		@car = Car.find(params[:id])
		@booking = Booking.new
	end

	def new 
		@car = Car.new
	end

	def create 
		@car = Car.create(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
	end 
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user      
  end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h1>Route to Index is working</h1>
<div class="wrapper-grey">
  <div class="container-wrap text-center light-grey-background">
    <h1>Car Listings</h1>
   <div class="row">
      <div class="col-xs-12">  
        <% @cars.sample(21).each do |car| %>
          <div class="col-xs-12 col-sm-4">
            <section id="content">
              <%= link_to "", car_path(car)%>
              <h4><%=car.brand%> <%=car.model%></h4>
              <% end %>
			</section>
			</div>
		</div>
	</div>
	</div>
</div>
<div class="container">
    <br><br><br><br><br>
    <h2 class="title"><span style="color:#25898b;">Discover your sound.</span></br>Rent musical cars, equipment, and gears.</h2>


    <section class="search-form">
      <%= simple_form_for :search, url: cars_path, method: "get", html: { class: 'form-inline' } do |f| %>
        <%= f.input :name, input_html: { class: 'search-input' }, label: false, placeholder: "What car are you looking for?" %>
        <%= f.submit class: 'search-btn' %>
      <% end %>
    </section>
    <br><br>

    <section class="gallery">
      <div class="row">
        <% @cars.each do |car| %>
          <div class="col-xs-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path car.photo.path %>)>
              <%= link_to car_path(car), class: 'card-link' do %><% end %>
              <div class="card-category"><%= car.brand + " " + car.model %></div>
              <div class="card-description">
                <p> <%= "$ #{car.price}" %> </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <% if @message %>
        <br>
        <br>
        <br>
        <p> <%= @message %> </p>
      <% end %>

    </section>
</div>

app/views/cars/show.html.erb
<div class="container">
<h1>Route to show is working.</h1>
<div class="search-bar">
    <form action="/cars" class="form-inline padded">
      <input type="text" class="form-control border-radius input-lg" placeholder="">
      <input type="text" name="checkin" class="form-control border-radius input-lg datepicker" placeholder="Checkin">
      <input type="text" name="checkout" class="form-control border-radius input-lg datepicker" placeholder="Checkout">
      </form>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('https://s4.aconvert.com/convert/p3r68-cdx67/jbhcq-j7qo2.jpg');">
    <header class="business-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1 class="display-3 text-center text-white mt-4">No Boring Cars Allowed</h1>
          </div>
        </div>
      </div>
    </header>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Facebook Login",omniauth_authorize_path(:user, :facebook), class: "navbar-wagon-item navbar-wagon-link " %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>